### ISSUE TITLE
Change Juniper Devices under HPE Manufacturer

### ISSUE THREAD

**Issue by moetezz** [netbox-community/devicetype-library#1912]
In the future Juniper devices' Manufacturer need to be labeled as HPE and No longer Juniper after the acquisition of HPE:
https://www.hpe.com/us/en/newsroom/press-release/2024/01/hpe-to-acquire-juniper-networks-to-accelerate-ai-driven-innovation.html

**Comment by kyerlasswell** [comment]
Unless I'm missing something, I don't see anything suggesting HP will dissolve Juniper a brand or even a company. I don't think this change is necessary unless they completely remove all Juniper branding when the acquisition goes through, especially if Juniper remains its own unique entity separate from HPE.

As a counter-point that already exists in this repo:

APC devices are all under the manufacturer "APC" instead of Schneider Electric. APC isn't technically the manufacturer, it's a brand under Schneider Electric, but it makes a lot more sense to list it under APC.

**Comment by DanSheps** [comment]
I agree, until something changes I think we will keep it as-is

**Comment by danner26** [comment]
We can leave it as is for now, but Juniper should me migrated under HPE at some point. We decided to do this for all sub-brands just like Meraki (Cisco), Tripp-Lite (Eaton), Aruba (HPE), etc.
