### ISSUE TITLE
Images for Devices

### ISSUE THREAD

**Issue by sHorst** [netbox-community/devicetype-library#625]
Hey,

is there a way to add Images (front and rear) to the yaml? I did not find a way. It could be a neat way for all the devices to also have images attached.

**Comment by ryanmerolle** [comment]
This was brought up before #212 .  I differ to @jeremystretch since I'm not sure a community project not affiliated with any of these vendors may or may enter some legal grey areas by hosting images of their products.

This may not be a big deal at all, and I'm just over-blowing the issue.  Frankly, this repo probably already is in a grey zone given it hosts models of vendor devices as it is.

**Comment by sHorst** [comment]
understandable ..

**Comment by jeremystretch** [comment]
We don't host images in this repo because they're generally protected by copyright and not licensed for redistribution. (And even the minority which may be free to redistribute typically require some form of attribution to the author which isn't feasible to maintain.)

> Frankly, this repo probably already is in a grey zone given it hosts models of vendor devices as it is.

Not at all. This repo is merely a collection of factual information (which by its nature cannot be copyrighted), curated by volunteers adhering to the terms of the asserted license.
